# Data types and arrays in NumPy

From: A.K.

##**Типы данных**

NumPy supports a greater variety of numeric types than pure Python. 

All data types are listed in the sctypeDict dictionary as keys, to see all available data types you can run the following command:

In [1]:
import numpy as np
np.sctypeDict

{0: numpy.bool_,
 1: numpy.int8,
 10: numpy.ulonglong,
 11: numpy.float32,
 12: numpy.float64,
 13: numpy.float128,
 14: numpy.complex64,
 15: numpy.complex128,
 16: numpy.complex256,
 17: numpy.object_,
 18: numpy.bytes_,
 19: numpy.str_,
 2: numpy.uint8,
 20: numpy.void,
 21: numpy.datetime64,
 22: numpy.timedelta64,
 23: numpy.float16,
 3: numpy.int16,
 4: numpy.uint16,
 5: numpy.int32,
 6: numpy.uint32,
 7: numpy.int64,
 8: numpy.uint64,
 9: numpy.longlong,
 '?': numpy.bool_,
 'B': numpy.uint8,
 'Bytes0': numpy.bytes_,
 'D': numpy.complex128,
 'Datetime64': numpy.datetime64,
 'F': numpy.complex64,
 'G': numpy.complex256,
 'H': numpy.uint16,
 'I': numpy.uint32,
 'L': numpy.uint64,
 'M': numpy.datetime64,
 'M8': numpy.datetime64,
 'O': numpy.object_,
 'P': numpy.uint64,
 'Q': numpy.ulonglong,
 'S': numpy.bytes_,
 'Str0': numpy.str_,
 'U': numpy.str_,
 'Uint64': numpy.uint64,
 'V': numpy.void,
 'a': numpy.bytes_,
 'b': numpy.int8,
 'b1': numpy.bool_,
 'bool': numpy.bool_,
 'bool8': nu

###**Объекты dtype**



> 1. bool_ : A logical type (true or false) stored as a byte.



In [3]:
import numpy as np
bool(10)

True

In [4]:
import numpy as np
bool(0)

False



> 2. int_ : The default integer type (the same as C long, usually either int64 or int32)
 * intc : Identical to C int (int32 or int64).
 * intp : Integer type used for indexing (same as C ssize_t, usually either int64 or int32).
 * int8 : Integer numbers in the range -128 to 127 (numbers of size 1 byte).
 * int16 : Integer numbers in the range -32768 to 32767, (2-byte numbers).
 * int32 : Integer numbers in the range -2147483648 to 2147483647, (numbers of size 4 bytes).
 * int64 : Integer numbers in the range -9223372036854775808 to 9223372036854775807, (numbers of size 8 bytes).
 * uint8 : Integer numbers in the range 0 to 255 (numbers of size 1 byte).
 * uint16 : Integer numbers between 0 and 65535 (2-byte numbers).
 * uint32 : Integer numbers in the range 0 to 4294967295 (4-byte numbers).
 * uint64 : Integer numbers in the range 0 to 18446744073709551615 (numbers of size 8 bytes).






In [7]:
np.int64(11)

11

In [8]:
np.int32(True)

1



> 3. float_ : 
 * Float16 : Half-precision real numbers: 1 bit of sign, 5 bits of exponent, 10 bits of mantissa (2-byte numbers).
 * Float32 : Single-precision real numbers: 1 bit sign, 8 bits exponent, 23 bits mantissa (4-byte numbers).
 * Float64 : Double-precision real numbers: 1 bit sign, 11 bits exponent, 52 bits mantissa (numbers of size 8 bytes).



In [9]:
np.float64(4567)

4567.0

In [10]:
np.float64(False)

0.0



> 4. complex_ :
 * complex64 : Complex numbers in which the real and imaginary parts are represented by two real numbers of type float32.
 * complex128 : Complex numbers in which the real and imaginary parts are represented by two real numbers of type float64.



In [11]:
np.complex64(239)

(239+0j)

###**Additional functions**



> Many functions in NumPy take the data type as an optional argument:



In [13]:
import numpy as np
a = np.arange(5, dtype = np.int64)
a

array([0, 1, 2, 3, 4])



> If you need information about a particular type of floating-point number, you can query it using finfo():


In [14]:
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

##**NumPy arrays**

###**One-dimensional arrays**

The main NumPy object is a homogeneous multidimensional array. Most often it is a one-dimensional sequence or a two-dimensional table, filled with elements of the same type, usually numbers, which are indexed by a tuple of positive integers. In NumPy, the elements of this tuple are called axes, and the number of axes the rank.

There are several ways to create an array, the simplest is to enter the array values manually:

In [15]:
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'int_')
print(a)

[[1 2 4]
 [5 8 7]]


In [16]:
b= np.array([[[0,1,2],[0,1,2]],[[3,4,5],[3,4,5]],[[6,7,8],[6,7,8]]], dtype= 'complex')
print(b)

[[[0.+0.j 1.+0.j 2.+0.j]
  [0.+0.j 1.+0.j 2.+0.j]]

 [[3.+0.j 4.+0.j 5.+0.j]
  [3.+0.j 4.+0.j 5.+0.j]]

 [[6.+0.j 7.+0.j 8.+0.j]
  [6.+0.j 7.+0.j 8.+0.j]]]


If you know the size of the array, but don't know the elements, then use the arrange function: it returns uniformly distributed values in a given interval, the step size can also be specified:

In [17]:
arr = np.arange(24).reshape(2, 3, 4) # reshape- is the shape of an array
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Below are the basic methods of creating arrays:

In [21]:
arr1= np.array([[6,0,6],[0,6,0]], dtype='float64')  # Manual array creation

arr2= np.zeros((3,3)) # Creating a 3x3 array filled with 0

arr3= np.ones((3,3), dtype = 'int') # creating a 3x3 array filled with 1

arr4= np.random.random((2,4)) # Creating a 2x4 array filled with random numbers

arr5= np.linspace(1,20, num=10) # Creating an array where the data is distributed by size

print('1)\n',arr1,'\n\n2)\n',arr2,'\n\n3)\n',arr3,'\n\n4)\n',arr4,'\n\n5)\n',arr5)


1)
 [[6. 0. 6.]
 [0. 6. 0.]] 

2)
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

3)
 [[1 1 1]
 [1 1 1]
 [1 1 1]] 

4)
 [[0.43454804 0.36837081 0.18579642 0.91990114]
 [0.8756117  0.9784639  0.70771459 0.86849503]] 

5)
 [ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


###**Two-dimensional arrays**

We can create an array using the np.arange() function, which is much like the range() function in Python. Then, we can change the shape of the array with the reshape() method:

In [22]:
a = np.arange(12)
a
a=a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
# or we can do it like this
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

The first axis (and index, respectively) are rows, the second axis are columns.

###**Three-dimensional arrays**

In fact, the real world is not at all limited to tables, vectors and matrices. There are also tensors, quaternions, and octaves. And it is more convenient to represent some data exactly in three- and four-dimensional representation.

In [24]:
a = np.arange(48).reshape(4, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

# NumPy array attributes

Often when working with arrays, you need to get information about the size of the array, the size of the elements or for example data types. The attributes of arrays are shown below:

In [29]:
a= np.array([[0,1,2],[3,4,5]])
print(a)
print("a.ndim - returns the number of array dimensions => ",a.ndim)
print("a.shape - returns tuple of array size => ",a.shape)
print("a.size - returns total number of array elements => ",a.size)
print("a.dtype - shows type of array items => ",a.dtype)
print("a.itemsize - returns the size of each item => ",a.itemsize)
print("a.sum - returns sum of array items => ",a.sum())
print("a.min - returns minimal element => ",a.min())
print("a.max - returns maximal element => ",a.max())

[[0 1 2]
 [3 4 5]]
a.ndim - returns the number of array dimensions =>  2
a.shape - returns tuple of array size =>  (2, 3)
a.size - returns total number of array elements =>  6
a.dtype - shows type of array items =>  int64
a.itemsize - returns the size of each item =>  8
a.sum - returns sum of array items =>  15
a.min - returns minimal element =>  0
a.max - returns maximal element =>  5




> 

