# Array operations in NumPy

From: A.K.

##**Create arrays from scratch**

> 1. Creating an array of integers of length 10, filled with zeros

In [1]:
import numpy as np
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

> 2. Creating a 3x5 array of floating point values, filled with ones

In [2]:
np.ones((3, 5), dtype=float)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

> 3. Creating a 3x5 array filled with value 17.03

In [3]:
np.full((3, 5), 17.03)

array([[17.03, 17.03, 17.03, 17.03, 17.03],
       [17.03, 17.03, 17.03, 17.03, 17.03],
       [17.03, 17.03, 17.03, 17.03, 17.03]])

> 4. Creating an array filled with a linear sequence starting with 0 and ending with 27 (not included), in steps of 3

In [5]:
np.arange(0, 27, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

> 5. Creating an array of five values, evenly spaced between 0 and 3

In [6]:
np.linspace(0, 3, 5)

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

> 6. Creating a 3x3 array of uniformly distributed random values from 0 to 1

In [7]:
np.random.random((3, 3))

array([[0.07308144, 0.77936948, 0.98681382],
       [0.26757707, 0.7212021 , 0.6605307 ],
       [0.98143862, 0.30350396, 0.26248089]])

> 7. Creating a 3x3 array of normally distributed random values with a median of 0 and a standard deviation of 1 

In [8]:
np.random.normal(0, 1, (3, 3))

array([[-0.31604147,  1.27142957,  0.64770383],
       [ 0.1396571 , -0.31588639, -0.25527984],
       [ 1.3710162 ,  0.58498143, -1.30358943]])

> 8. Creating a 3x3 array of random integers between [0, 17]

In [9]:
np.random.randint(0, 17, (3, 3))

array([[16,  9, 15],
       [16,  6,  6],
       [ 8,  5,  6]])

> 9. Creating a 4x4 unit matrix

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

##**Array Attributes**

Array attributes - defining the size, shape, memory usage, and data types of arrays.

Let's create three arrays: one-dimensional, two-dimensional and three-dimensional.

In [11]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))
print('x1 - ', x1, '\n')
print('x2 - ', x2, '\n')
print('x3 - ', x3, '\n')

x1 -  [5 0 3 3 7 9] 

x2 -  [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

x3 -  [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]] 



Each of the arrays has the attributes dimension (ndim), size of each dimension (shape) and total size of the array (size):

In [12]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


##**Array indexing**

Array indexing is getting and setting values of individual array elements.

In [13]:
print('Whole array:', x1)
print('1st array element -',x1[0])
print('5th array element -',x1[4])

Whole array: [5 0 3 3 7 9]
1st array element - 5
5th array element - 7


Negative indices can be used to index from the end of the array:

In [14]:
print('Whole array:', x1)
print('1st end element -', x1[-1])
print('2nd end element -', x1[-2])

Whole array: [5 0 3 3 7 9]
1st end element - 9
2nd end element - 7


The elements in a multidimensional array can be accessed using comma-separated tuples of indices:

In [15]:
# Don't forget that indexing starts from zero
print('Whole array:\n', x2, '\n')
print('Item 0x0 -', x2[0, 0])
print('Item 2x0 -', x2[2, 0])
print('Item 2x-1 -', x2[2, -1])

Whole array:
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

Item 0x0 - 3
Item 2x0 - 1
Item 2x-1 - 7


You can also change the values in the arrays by indexes:

In [16]:
print('Initial array:\n', x2, '\n')
x2[0, 0] = 12
print('Modified array:\n', x2)

Initial array:
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

Modified array:
 [[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Remember that NumPy arrays have a fixed data type, so if the array contains integers, replacing one of the integers with a floating-point integer will not work, it will be truncated.

In [17]:
print('Initial array:\n', x1, '\n')
x1[0] = 2.72
print('Modified array:\n', x1)

Initial array:
 [5 0 3 3 7 9] 

Modified array:
 [2 0 3 3 7 9]


##**Array Slicing**

Array slicing is getting and setting values of sub-arrays within a large array.

Similar to accessing individual array elements, you can use square brackets to access subarrays with slicing. To access a slicing array x, use the syntax:

x[start:end:step] 

If any of these values are not specified, the defaults apply: start = 0, end = size of the corresponding dimension, step = 1.

In [18]:
x = np.arange(10)
print('Initial array -', x)
print('First five elements -', x[:5])
print('Elements after index 5 -', x[5:]) 
print('Subarray from the middle -', x[4:7]) 
print('Every second element -', x[::2])
print('Every second element starting from index 1 -', x[1::2])

Initial array - [0 1 2 3 4 5 6 7 8 9]
First five elements - [0 1 2 3 4]
Elements after index 5 - [5 6 7 8 9]
Subarray from the middle - [4 5 6]
Every second element - [0 2 4 6 8]
Every second element starting from index 1 - [1 3 5 7 9]


##**Creation of array copies**

The copy() method can be used to make a copy of an array, which is sometimes useful:

In [19]:
print('x2:\n', x2, '\n')
x2_copy = x2[:2, :2].copy()
print('x2_copy:\n', x2_copy)

x2:
 [[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]] 

x2_copy:
 [[12  5]
 [ 7  6]]


Now if you change this subarray, the original array remains unchanged: 

In [20]:
x2_copy[0, 0] = 803
print('x2_copy:\n', x2_copy, '\n')
print('x2:\n', x2)


x2_copy:
 [[803   5]
 [  7   6]] 

x2:
 [[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


##**Changing the shape of arrays**

Changing the shape of arrays is done by the reshape() method. For example, if we want to put a number from 1 to 9 into a 3x3 array, we can do it as follows:

In [22]:
arsh = np.arange(1, 10).reshape((3, 3))
print('arsh:\n', arsh)


arsh:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Another commonly used reshape pattern is to convert a one-dimensional array to a two-dimensional row matrix or column matrix. You can use the reshape method for this, but it is better to use the newaxis keyword when performing a slice operation: 

In [23]:
x = np.array([1, 2, 3]) 
print(x.reshape((1, 3)))    # Conversion to vector-string 
print(x[np.newaxis, :])     

[[1 2 3]]
[[1 2 3]]


In [24]:
print(x.reshape((3, 1)))   # Conversion to vector-column
print('\n',x[:, np.newaxis])    

[[1]
 [2]
 [3]]

 [[1]
 [2]
 [3]]


##**Array merging**

Merging or joining two arrays in NumPy is mostly done using np.concatenate, np.vstack and np.hstack methods. The np.concatenate method takes a tuple or a list of arrays as the first argument:

In [25]:
x = np.array([4, 6, 8])
y = np.array([8, 6, 4])
print('x + y =', np.concatenate([x, y]))

x + y = [4 6 8 8 6 4]


You can merge more than two arrays at the same time:

In [26]:
z = [77, 88, 99]
print('x + y + z =', np.concatenate([x, y, z]))

x + y + z = [ 4  6  8  8  6  4 77 88 99]


You can also use np.concatenate to merge two-dimensional arrays: 

In [27]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
print('Merging along the first coordinate axis:\n', np.concatenate([grid, grid]), '\n')
print('Merging along the second coordinate axis:\n', np.concatenate([grid, grid], axis=1))

Merging along the first coordinate axis:
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]] 

Merging along the second coordinate axis:
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


To work with arrays with different dimensions, it is more convenient and clear to use the functions np.vstack (vertical join) and np.hstack (horizontal join):

In [28]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])
print('Join arrays vertically:\n', np.vstack([x, grid]), '\n')
y = np.array([[99], [99]])
print('Join arrays horizontally:\n', np.hstack([grid, y]))


Join arrays vertically:
 [[1 2 3]
 [9 8 7]
 [6 5 4]] 

Join arrays horizontally:
 [[ 9  8  7 99]
 [ 6  5  4 99]]


##**Array splitting**

The opposite of merge is splitting, which is done with the functions np.split, np.hsplit and np.vsplit. You need to pass a list of indexes to them, which specify the split points: 

In [29]:
x = [1, 2, 3, 77, 99, 33, 22, 11]
x1, x2, x3 = np.split(x, [3, 5])
print('x1 -', x1)
print('x2 -', x2)
print('x3 -', x3)


x1 - [1 2 3]
x2 - [77 99]
x3 - [33 22 11]


In [30]:
# other examples of splitting

grid = np.arange(16).reshape((4, 4))
print('grid:\n', grid, '\n')
upper, lower = np.vsplit(grid, [2])
print('upper:\n', upper, '\n')
print('lower:\n', lower, '\n')
left, right = np.hsplit(grid, [2])
print('left:\n', left, '\n')
print('right:\n', right)

grid:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

upper:
 [[0 1 2 3]
 [4 5 6 7]] 

lower:
 [[ 8  9 10 11]
 [12 13 14 15]] 

left:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

right:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


##**Broadcasting**

For arrays of the same size, binary operations are performed element by element:

In [32]:
a = np.array([0, 1, 3])
b = np.array([7, 7, 7])
print('a: ', a)
print('b: ', b)
print('a + b =', a + b) 

a:  [0 1 3]
b:  [7 7 7]
a + b = [ 7  8 10]


You can also easily add a scalar value to an array:

In [33]:
print('a: ', a)
print('a + 11 =', a + 11)

a:  [0 1 3]
a + 11 = [11 12 14]


Similarly, we can extend the broadcast to arrays of larger dimensions:

In [34]:
M = np.full((3, 3), 5)
print('M:\n', M, '\n')
print('a:', a, '\n')
print('M + a =\n', M + a)

M:
 [[5 5 5]
 [5 5 5]
 [5 5 5]] 

a: [0 1 3] 

M + a =
 [[5 6 8]
 [5 6 8]
 [5 6 8]]


Here the one-dimensional array a is stretched (broadcasted) into a second dimension to fit the shape of the array M. More complex cases may involve broadcasting both arrays:

In [35]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print('a:', a, '\n')
print('b:\n', b, '\n')
print('a + b =\n', a + b)

a: [0 1 2] 

b:
 [[0]
 [1]
 [2]] 

a + b =
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


Broadcasting in NumPy follows a strict set of rules defining the interaction between two arrays.

**Rule 1**: if the dimensionality of the two arrays differs, the shape of the array with the smaller dimensionality is augmented with units on the left side.

**Rule 2**: If the shape of the two arrays doesn't match in some dimension, the array with a shape equal to 1 in that dimension is stretched to match the shape of the other array.

**Rule 3**: If the sizes of the arrays differ in any dimension and neither of them equals 1, an error is generated. 

###**Additionally**

In [36]:
#Product of the elements of both arrays
a = np.array([[1,2], [0,9]])
print(a)
b = np.array([[2,11],[3,7]])
print(b)
a * b


[[1 2]
 [0 9]]
[[ 2 11]
 [ 3  7]]


array([[ 2, 22],
       [ 0, 63]])

In [37]:
#The matrix product of both arrays
a = np.array([[1,1], [0,1]])
print(a)
b = np.array([[2,0],[3,4]])
print(b)
a @ b 

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


array([[5, 4],
       [3, 4]])

In [38]:
#Move the array axis to the specified positions
a = np.arange(24).reshape(3, 2, 4)
print(a)
b = np.moveaxis(a, 0, 1)
b

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23]]])

In [39]:
#Put the specified axis first or in the specified position
a = np.arange(24).reshape(2, 3, 4)
print(a)
b = np.rollaxis(a, 0, 2)
b

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [40]:
#Swap the two specified axes of the array
a = np.arange(24).reshape(2, 3, 4)
print(a)
b = np.swapaxes(a, 0, 2)
b 

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [42]:
#Conversion of input data into a one-dimensional array
np.atleast_1d(1, 2, 3, 4, 5)

[array([1]), array([2]), array([3]), array([4]), array([5])]

In [44]:
#Add a new axis to the array. 
a = np.array([1, 2, 3])
print(a)
np.expand_dims(a, axis = 1) 

[1 2 3]


array([[1],
       [2],
       [3]])

In [46]:
#Create an array by repeating the specified array "a" a specified number of times 
a = np.array([1, 7])
np.tile(a, 3)

array([1, 7, 1, 7, 1, 7])

In [47]:
#Repeat array elements 
a = np.array([8, 3])
np.repeat(a, 3)

array([8, 8, 8, 3, 3, 3])

In [48]:
#Remove the specified elements on the specified axis
a = np.arange(9)
print(a)
np.delete(a, 0)

[0 1 2 3 4 5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
#Put the specified items before the specified indexes on the specified axis
a = np.arange(8)
print(a)
np.insert(a, 3, [11, 13])

[0 1 2 3 4 5 6 7]


array([ 0,  1,  2, 11, 13,  3,  4,  5,  6,  7])

In [52]:
#Add elements to the end of the array
a = np.array([1, 2, 8, 6])
np.append(a, 19)

array([ 1,  2,  8,  6, 19])

In [53]:
a = np.array([0, 0, 0, 7, 5, 9, 0, 0, 0])
print(np.trim_zeros(a)) # Remove zeros from the beginning and end
print(np.trim_zeros(a, 'f')) # Remove zeros from the beginning only
print(np.trim_zeros(a, 'b')) #Remove zeros from the end only

[7 5 9]
[7 5 9 0 0 0]
[0 0 0 7 5 9]


In [54]:
#Find unique elements of the array
np.unique([1, 17, 17, 17, 13, 7, 7, 7])

array([ 1,  7, 13, 17])

In [55]:
#Put the elements in reverse order along the specified axis without changing the size of the array
a = np.array([2, 3, 15, 17])
np.flip(a)

array([17, 15,  3,  2])

In [56]:
a = np.array([[0,3,0],[7,0,4],[0,9,0]])
print(a)
#Turn 90 degrees counterclockwise
print(np.rot90(a))
#Turn 90 degrees clockwise
print(np.rot90(a, k = -1))  

[[0 3 0]
 [7 0 4]
 [0 9 0]]
[[0 4 0]
 [3 0 9]
 [0 7 0]]
[[0 7 0]
 [9 0 3]
 [0 4 0]]
