# Indexing and sorting arrays in NumPy

From: K.A.

In [1]:
# of course
import numpy as np

##Array indexing

In NumPy, as in pure Python, you can use numbers to access items. **Indexing starts with 0**. Negative indexes can be used for indexing.

In [4]:
a = np.arange(7)
print('Initial array\n',a)
print('Result:', a[3])
print('Result with a negative index:', a[-3])

Initial array
 [0 1 2 3 4 5 6]
Result: 3
Result with a negative index: 4


But, unlike standard Python, you can access elements of two-dimensional arrays by writing the element numbers separated by commas.

In [5]:
b = np.arange(9).reshape(3, 3)
print('Initial array\n', b)
print('Result:', b[2, 0])
print('Result with a negative index:', b[-2, 1])

Initial array
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Result: 6
Result with a negative index: 4


The same indexing that was used before is used to change values.

In [6]:
print('For one-dimensional array:\n', a)
a[0] = 9
print('\n', a)
print('\nFor two-dimensional arrays:\n', b)
b[1, 1] = 9
print('\n',b)

For one-dimensional array:
 [0 1 2 3 4 5 6]

 [9 1 2 3 4 5 6]

For two-dimensional arrays:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[0 1 2]
 [3 9 5]
 [6 7 8]]


But unlike Python lists, NumPy arrays have a fixed data type.

In [7]:
print('For one-dimensional array:\n', a)
a[0] = 2.72
print('\n', a)

For one-dimensional array:
 [9 1 2 3 4 5 6]

 [2 1 2 3 4 5 6]


##Array sorting

To sort arrays, the sort function is used with the axis parameter, which is used to determine the type of sorting. For example, for a two-dimensional array, "0" means sorting by columns, and "1" - by rows.

In [8]:
a = np.array([1, 3, 5, 4, 7, 13])
print('Initial array - ', a)
a = np.sort(a)
print('Sorted array - ', a)
b = np.random.randint(0, 100, size = (5, 5))
print(b)
print('Sorting by columns - ', np.sort(b, axis = 0))
print('Sorting by rows - ', np.sort(b, axis = 1))

Initial array -  [ 1  3  5  4  7 13]
Sorted array -  [ 1  3  4  5  7 13]
[[91 55  5 84 79]
 [35 86 27 79 94]
 [35 55 41 92  9]
 [ 9 65 25 40 33]
 [88 76 39 71  4]]
Sorting by columns -  [[ 9 55  5 40  4]
 [35 55 25 71  9]
 [35 65 27 79 33]
 [88 76 39 84 79]
 [91 86 41 92 94]]
Sorting by rows -  [[ 5 55 79 84 91]
 [27 35 79 86 94]
 [ 9 35 41 55 92]
 [ 9 25 33 40 65]
 [ 4 39 71 76 88]]


The function lexsort performs reverse sorting based on the specified keys (lexicographic sorting). 

In [9]:
a = np.array([1, 5, 4, 2, 17, 3])
b = np.array([3, 6, 3, 1, 6, 7])
c = np.lexsort((a, b))
[(a[i], b[i]) for i in c]

[(2, 1), (1, 3), (4, 3), (5, 6), (17, 6), (3, 7)]